# Generated by Django 6.0.6 on 2026-06-27 03:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'providers',
                'ordering': ['normalized_name'],
            },
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('started', 'Started'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='started', max_length=20)),
                ('source_file', models.CharField(blank=True, max_length=500)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('skipped_rows', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ingestion_jobs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', 'started_at'], name='idx_job_status_started')],
            },
        ),
        migrations.CreateModel(
            name='RawResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_response_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('raw_data', models.JSONField()),
                ('source_url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingestion_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_responses', to='rates.ingestionjob')),
            ],
            options={
                'db_table': 'raw_responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rate_type', models.CharField(db_index=True, max_length=50)),
                ('rate_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('effective_date', models.DateField(db_index=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('ingestion_ts', models.DateTimeField(help_text='Original ingestion timestamp from source data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='rates.provider')),
                ('raw_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='rates.rawresponse')),
            ],
            options={
                'db_table': 'rates',
                'ordering': ['-effective_date', '-ingestion_ts'],
            },
        ),
        migrations.AddIndex(
            model_name='rawresponse',
            index=models.Index(fields=['status', 'created_at'], name='idx_raw_status_created'),
        ),
        migrations.AddIndex(
            model_name='rate',
            index=models.Index(fields=['provider', 'rate_type'], name='idx_rate_provider_type'),
        ),
        migrations.AddIndex(
            model_name='rate',
            index=models.Index(fields=['rate_type', 'effective_date'], name='idx_rate_type_date'),
        ),
        migrations.AddIndex(
            model_name='rate',
            index=models.Index(fields=['created_at'], name='idx_rate_created_at'),
        ),
        migrations.AddIndex(
            model_name='rate',
            index=models.Index(fields=['provider', 'rate_type', 'effective_date'], name='idx_rate_provider_type_date'),
        ),
        migrations.AddConstraint(
            model_name='rate',
            constraint=models.UniqueConstraint(fields=('provider', 'rate_type', 'effective_date', 'ingestion_ts'), name='uq_rate_provider_type_date_ts'),
        ),
    ]
